os:
  -
    distribution: Debian GNU/Linux
    versions:
      10: &debian10
        defaultPackageManager: apt-get
        silentMode: -qq
        packageManagerCommands:
          -
            cmd: preSettings
            app: echo
            arg: "'debconf debconf/frontend select Noninteractive' | debconf-set-selections"
          -
            cmd: update
            app: apt-get
            arg: -qq update
          -
            cmd: upgrade
            app: apt-get
            arg: -qq upgrade
          -
            cmd: install
            app: apt-get
            arg: -qq install
          -
            cmd: uninstall
            app: apt-get
            arg: -qq remove
      11: *debian10
  -
    distribution: ubuntu
    versions:
      20.04: *debian10
